# Generated by Django 3.0.7 on 2020-06-21 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 6, 30, 43, 417026, tzinfo=utc)),
        ),
    ]
