# Generated by Django 3.0.7 on 2020-06-21 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200621_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 6, 47, 42, 455527, tzinfo=utc)),
        ),
    ]
