# Generated by Django 3.0.7 on 2020-07-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='color',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='m2_slot',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='manufacturer',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='mem_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='mem_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='msata_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='on_ethernet',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='on_video',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='part',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_16_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_1_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_4_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_8_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='raid_supp',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sata_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sli',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='support_ecc',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_2_0_head',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_head_gen1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_head_gen2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2_head_gen2x2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='wireless_net',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='mem_type',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
