# Generated by Django 3.0.3 on 2020-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_auto_20200703_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='mem_cap',
        ),
        migrations.AddField(
            model_name='ram',
            name='cas_latency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='color',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='ecc_reg',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='form_factor',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='fw_latency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='heat_spread',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='part',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='timing',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ram',
            name='voltage',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ram',
            name='mem_type',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
