# Generated by Django 3.0.3 on 2020-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_auto_20200703_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='form_factor',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='storage',
            name='manufacturer',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='storage',
            name='nvme',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='storage',
            name='part',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='storage',
            name='str_interface',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
