# Generated by Django 3.0.3 on 2020-07-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_auto_20200703_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=150)),
                ('cpu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Cpu')),
                ('mtb_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Motherboard')),
                ('ram_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Ram')),
                ('str_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Storage')),
                ('vga_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Vga')),
            ],
        ),
    ]
