# Generated by Django 3.0.7 on 2020-08-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0010_auto_20200813_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='cpu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Cpu'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='mtb_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Motherboard'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ram_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Ram'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='str_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Storage'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='vga_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.Vga'),
        ),
    ]
